# Generated by Django 6.1.2 on 2026-10-08 15:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(db_index=True, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('guardian_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Enter a valid phone number (10-15 digits).')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to=events.models.child_photo_upload_path)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
                'ordering': ['registration_id'],
            },
        ),
        migrations.CreateModel(
            name='EventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Navratri 2026', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('total_days', models.IntegerField(default=20)),
                ('current_day', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Configuration',
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_day', models.IntegerField()),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.child')),
            ],
            options={
                'verbose_name': 'Daily Attendance',
                'verbose_name_plural': 'Daily Attendances',
                'ordering': ['event_day', 'entry_time'],
                'constraints': [models.UniqueConstraint(fields=('child', 'event_day'), name='unique_child_day_attendance')],
                'unique_together': {('child', 'event_day')},
            },
        ),
        migrations.CreateModel(
            name='DailyGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_day', models.IntegerField()),
                ('gift_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('GIVEN', 'Given'), ('PENDING', 'Pending')], default='GIVEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.child')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Gift',
                'verbose_name_plural': 'Daily Gifts',
                'ordering': ['event_day', 'gift_time'],
                'constraints': [models.UniqueConstraint(fields=('child', 'event_day'), name='unique_child_day_gift')],
                'unique_together': {('child', 'event_day')},
            },
        ),
    ]
