# Generated by Django 6.1.2 on 2026-10-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='registration_id',
            field=models.CharField(db_index=True, editable=False, max_length=6, unique=True),
        ),
    ]
