# Generated by Django 6.1.2 on 2026-10-09 14:21

from django.db import migrations, models


def update_existing_registration_ids(apps, schema_editor):
    Child = apps.get_model('events', 'Child')
    for child in Child.objects.all():
        rid = str(child.registration_id).strip()
        if not rid.startswith('2026-'):
            child.registration_id = f'2026-{rid}'
            child.save(update_fields=['registration_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_numeric_registration_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['id'], 'verbose_name': 'Child', 'verbose_name_plural': 'Children'},
        ),
        migrations.AlterField(
            model_name='child',
            name='registration_id',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.RunPython(update_existing_registration_ids, migrations.RunPython.noop),
    ]
